import './env.js';
import './angular/app.js';
import './angular/configure.js';
import './angular/factories.js';
import './angular/directives.js';
import './angular/general_controllers.js';
import './angular/app.controllers.js';
import './angular/controllers.js';
import './angular/skeleton-loading.js';